//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvidencijaPotrosnjeEntities : DbContext
    {
        public EvidencijaPotrosnjeEntities()
            : base("name=EvidencijaPotrosnjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StateConsumption> StateConsumptions { get; set; }
        public virtual DbSet<StateInfo> StateInfoes { get; set; }
        public virtual DbSet<StateWeather> StateWeathers { get; set; }
    }
}
