//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateConsumption
    {
        public int Id { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CovRatio { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateShort { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> DateUTC { get; set; }
        public string StateCode { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> ValueScale { get; set; }
    
        public virtual StateInfo StateInfo { get; set; }
    }
}
