//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateWeather
    {
        public int Id { get; set; }
        public int StateId { get; set; }
        public Nullable<double> AirTemperature { get; set; }
        public string CloudCover { get; set; }
        public Nullable<int> DevpointTemperature { get; set; }
        public Nullable<int> GustValue { get; set; }
        public string HorizontalVisibility { get; set; }
        public Nullable<int> Humidity { get; set; }
        public string PresentWeather { get; set; }
        public Nullable<double> ReducedPressure { get; set; }
        public Nullable<double> StationPressure { get; set; }
        public string WindDirection { get; set; }
        public Nullable<int> WindSpeed { get; set; }
    
        public virtual StateInfo StateInfo { get; set; }
    }
}
