///////////////////////////////////////////////////////////
//  StateInfo.cs
//  Implementation of the Class StateInfo
//  Generated by Enterprise Architect
//  Created on:      27-Apr-2021 11:04:37 PM
//  Original author: Dušan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class StateInfo {

	public StateWeather m_StateWeather;
	public StateConsumption m_StateConsumption;

	public StateInfo(){

	}

	~StateInfo(){

	}

	/// 
	/// <param name="stateWeather"></param>
	/// <param name="stateConsumption"></param>
	public StateInfo(StateWeather stateWeather, StateConsumption stateConsumption){

	}

}//end StateInfo